[package]
name = "pulsebeam-webrtc-sys"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
links = "pulsebeam_webrtc"
publish = false

[features]
native = []

[dependencies]
cxx = { version = "=1.0.200", path = "vendor/cxx" }

[dev-dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"

[build-dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
